### ISSUE TITLE
library invalid

### ISSUE THREAD

**Issue by detmer87** [MikroElektronika/LoRa_click#1]
If I try to add the libray as a Zip Adruino states that the library is invalid.

When I just manualy add the extracted folder "Click_LoRa_RF-master" to my libraries Adruino sees the library but again states that the library is invalid.

How can I fix this? I want to have the official librabry on my PC so I can setup my Click Lora.

Thanks in advance,

**Comment by mvidoje** [comment]
Hello there,
Library is written for mikroC compilers, however it can be ported to arduino avr-gcc compiler. All you have to do is to wrap arduino "serial_write" function using hal_uart_write function provided in HAL, also you have to replace mikroC specific types and to implement GPIO functions according to your hardware design.
Also UART interrupt should be replaced with polling implementation or identical isr.

Best Regards,
Milos
